# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_MEMORY = "512"
VMNAME = "synd_vm"

PGPORT = "5432"
PGUSER = "postgres"
PGPASSWORD = "devved"
PGDATABASE = "synd_test"
PGVERSION = "12"
NODE_VER = "12.x"
APP_DIR = "/home/vagrant/synd"
DB_DIR = APP_DIR + "/database/migrations/"

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
ETH0IP=$(ifconfig -a eth0 | grep "inet addr:")
echo "Networking: [$ETH0IP]"
SCRIPT

Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |vb, orvb|
		orvb.vm.synced_folder '../', APP_DIR, create:true, :mount_options => ['dmode=775', 'fmode=777']
		orvb.vm.network "private_network", ip: "192.168.86.5"
		vb.memory = SERVER_MEMORY
		vb.customize ["modifyvm", :id, "--memory", SERVER_MEMORY]
	end

	config.vm.provider "hyperv" do |hv, orhv|
		orhv.vm.synced_folder "../", APP_DIR, create:true, type: "smb" #, rsync__exclude: ".git/"
		orhv.vm.network "public_network"
		hv.memory = SERVER_MEMORY
		hv.maxmemory = SERVER_MEMORY
		hv.enable_virtualization_extensions = true
		hv.vmname = VMNAME
	end

	config.vm.define "testbox", primary:true do |testbox|
		testbox.vm.box = "generic/ubuntu1604"
		testbox.vm.hostname = "synd.dev"
		testbox.vm.provision "shell", inline: $script
		testbox.vm.provision :shell do |s|
			s.path = "testbox.bootstrap.sh"
			s.env = {
				"PGPORT" => PGPORT,
				"PGUSER" => PGUSER,
				"PGPASSWORD" => PGPASSWORD,
				"PGDATABASE" => PGDATABASE,
				"PGVERSION" => PGVERSION,
				"NODE_VER" => NODE_VER,
				"APP_DIR" => APP_DIR,
				"DB_DIR" => DB_DIR
			}
		end
	end
end
